### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Notaghost9997** [xhlove/mpd-content-parser#3]
i am getting this error 
```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\itmuz\Videos\wv\mpd-content-parser-master\mpd_content_parser.py", line 449, in <module>
    main()
  File "C:\Users\itmuz\Videos\wv\mpd-content-parser-master\mpd_content_parser.py", line 443, in main
    parser.generate()
  File "C:\Users\itmuz\Videos\wv\mpd-content-parser-master\mpd_content_parser.py", line 287, in generate
    self.mediaPresentationDuration = self.match_duration(mediaPresentationDuration)
  File "C:\Users\itmuz\Videos\wv\mpd-content-parser-master\mpd_content_parser.py", line 280, in match_duration
    duration = re.match("PT(\d+)H(\d+)M(\d+)(\.?\d+)S", duration)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

what i am doing wrong?
i already installed the requirements and i am using updated python version

**Comment by xbstory** [comment]
I need mpd file.

**Comment by Notaghost9997** [comment]
It was from https://bitmovin.com/demos/drm

**Comment by Notaghost9997** [comment]
nvm i found some other program that does the same thing

**Comment by xbstory** [comment]
```bash
python mpd_content_parser.py -p 11331.mpd -baseurl https://bitmovin-a.akamaihd.net/content/art-of-motion_drm/mpds
```
 fixed.
