### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by pandamoon21** [xhlove/mpd-content-parser#8]
Hi, I'm facing this issue when I tried to parse this dash URL
`https://cdn-telkomsel-01.akamaized.net/Content/DASH/VOD/4868/4960/7fc7f05a-0038-4c9f-a018-478d021645cc/f08ee767-61d6-e112-ae04-d8d25c23edb7/manifest.mpd`
or this one,
[manifest.zip](https://github.com/xhlove/mpd-content-parser/files/7189754/manifest.zip)
```
E:\Software\mpd-content-parser\mpd-content-parser>mpd_content_parser.py -p manifest.mpd
Traceback (most recent call last):
  File "E:\Software\mpd-content-parser\mpd-content-parser\mpd_content_parser.py", line 305, in <module>
    main()
  File "E:\Software\mpd-content-parser\mpd-content-parser\mpd_content_parser.py", line 293, in main
    tracks = parser.parse(args.baseurl)
  File "E:\Software\mpd-content-parser\mpd-content-parser\mpd_content_parser.py", line 120, in parse
    self.generate(baseurl, _Period, _AdaptationSet, _Representation)
  File "E:\Software\mpd-content-parser\mpd-content-parser\mpd_content_parser.py", line 181, in generate
    _initialization = _SegmentTemplate.get_initialization()
  File "E:\Software\mpd-content-parser\mpd-content-parser\utils\childs\segmenttemplate.py", line 23, in get_initialization
    return self.initialization.replace('..', '')
AttributeError: 'NoneType' object has no attribute 'replace'
```
The manifest can't be parsed properly.

**Comment by pandamoon21** [comment]
While XstreamDL-CLI works fine

**Comment by xbstory** [comment]
yeah, this project is stopped.

you can use XstreamDL-CLI with --parse-only option

**Comment by pandamoon21** [comment]
> yeah, this project is stopped.
> 
> you can use XstreamDL-CLI with --parse-only option

Alright, I got it. Thanks.
